### ISSUE TITLE
10024: Connection refused

### ISSUE THREAD

**Issue by solaim** [bestwu/ewomail#3]
使用内部配置进行邮件收发测试时：

`This is the mail system at host mail.dev.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<test@dev.com>: connect to 127.0.0.1[127.0.0.1]:10024: Connection refused`

hosts配置如下：
`127.0.0.1		mail.dev.com smtp.dev.com imap.dev.com dev.com`

**Comment by blkfhusky** [comment]
同问

**Comment by crackwei** [comment]
两年了，竟然没有一个人回答这个问题，Google只搜到问题，搜不到答案，不知道这个项目是怎么维持的~~~
最后，我只能自己解决了。这个问题的产生是因为docker不支持IPV6，导致amavisd服务不能启动。解决方法也很简单，只要在/etc/amavisd.conf文件中加入一行：
    $inet_socket_bind = '127.0.0.1';

这样就可以了！
