### ISSUE TITLE
设置域名DNS  的页面在哪儿，愣是找不到

### ISSUE THREAD

**Issue by CharmWang** [bestwu/ewomail#7]
基本上运行好了，但是这个设置域名DNS的页面找不到，导致无法测试发送邮件...

能否将入口截图下？ 感谢！

**Comment by bestwu** [comment]
在你的域名注册商后台域名解析处

**Comment by CharmWang** [comment]
现在在rainloop页面配置了一个域名： xx.com , 在imap那里填写的127.0.0.1 ，smap那里填写的是公司邮件服务器的地址(不需要验证就能访问)，点击测试后是ok的，但是给  test@xx.com发送邮件时，直接发送不出去...  

这是什么原因？ 背景：docker镜像里面启动的，按照你的hub操作的

**Comment by CharmWang** [comment]
docker exec cmemail amavisd testkeys
TESTING#1: dkim._domainkey.xxx.com       => invalid (public key: not available)

这个错误应该如何解决？ 

感谢你的回复.

**Comment by CharmWang** [comment]
目前问题已解决

个人觉得既然已提供hub容器，建议将一些步骤写的更加清楚些.
